### ISSUE TITLE
Assertion `s.length == ColsPerWeek` doesn't hold when ColsPerDay = 5

### ISSUE THREAD

**Issue by johannes-riecken** [quickfur/dcal#2] opened 2022-03-11 07:30 UTC
I had great fun translating your example to Haskell, but I think something with the ColsPerDay logic is broken?

`.map!(s => format(" %.*s", ColsPerDay, s))`

Given that the weekday names all have a size of two, I think using %.*s, which only adjusts the maximum length, is a strange choice. If I change ColsPerDay to 5, I get an assertion error.

**Comment by quickfur** [comment] 2022-03-11 17:31
Thanks for the bug report!

You're quite right, it should be `" %*s"` instead of `" %.*s"`.  The assertion, though, was caused by a separate bug: a width of 2 was hard-coded into the code that formats the weekday heading, rather than based on `ColsPerDay`.

Both issues should have been fixed in the latest commit.  Please reopen if I missed anything.

**Closed by quickfur** 2022-03-11 17:31 UTC
